React Front End
python-42/fast-fish pull request #6
Opened 2023-04-28 17:39 UTC by jagernet-ops

# React Front End Pull Request
## Assignee: MJS
### Info-for-Herrmann:
Inside of this PR entails all details of the React development. I decided to use NextJS as our manager. Assign issues accordingly!

2023-05-05 14:42 UTC, jherrmann06 commented
Is this ready for review?

2023-05-05 15:03 UTC, jagernet-ops commented
> Is this ready for review?

You can merge the current changes. The web app has placeholder values currently.

2023-05-05 15:32 UTC, python-42 requested changes
Mostly looks good, just a tiny change

2023-05-05 15:32 UTC, python-42 commented on fast-fish/public/manifest.json
> +  "short_name": "React App",
Change to "Fast Fish"

2023-05-05 15:32 UTC, jherrmann06 commented on fast-fish/public/manifest.json
> +  "name": "Create React App Sample",
Change to a longer name including "Fast Fish"

2023-05-05 18:45 UTC, jagernet-ops commented
> Mostly looks good, just a tiny change

I have implemented the change to the manifest file's name, I deleted the old src folder which I glossed over(oops), and I changed the logo images within the public folder to be fishes of different sizes!

2023-05-10 14:49 UTC, jherrmann06 approved these changes
Already did a more informal review in person so I just skimmed this. Looks good

2023-05-10 14:49 UTC, merged